name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
exclude-labels:
  - 'configuration'
  - 'tooling'
version-resolver:
  major:
    labels:
      - 'major-change'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'translation'
      - 'feat'
      - 'documentation'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

  - title: '📝 Documentation'
    labels:
      - 'documentation'

  - title: '🌐 Translations'
    labels:
      - 'translation'

  - title: ':arrow_up: Dependencies'
    label: 'dependencies'
    collapse-after: 1

change-template: '- [#$NUMBER] $TITLE @$AUTHOR'
sort-direction: ascending

template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
