name: Release Drafter

on:
  push:
    branches:
      - main

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    outputs:
      upload_url: ${{ steps.release_drafter.outputs.upload_url }}
    steps:
      - id: release_drafter
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

  
  upload-asset:
    name: Test build
    runs-on: ubuntu-latest
    needs: update_release_draft
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Upload built card to draft release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.update_release_draft.outputs.upload_url }}
          asset_path: dist/solar-card.js
          asset_name: solar-card.js
          asset_content_type: application/javascript

  
